config/routes.rb
Ide::Application.routes.draw do

  get '/directories/get_tree', to: 'directories#get_tree'
  post '/projects/setSession', to: 'projects#setSession'
  resources :directories
  delete '/directories', to: 'directories#destroy'

  resources :data_sets, controller: 'files', path: 'files'

  get '/projects/:action', to: 'projects#:action', constraints: {action: /open|close/i}
  resources :projects

  root 'projects#index'
  get '/:project', to: 'directories#index', constraints: {project: /[-_.a-z0-9а-яёЁ%]+/i}

  get 'file/:action', to: 'files#:action', constraints: {action: /index|new_(?:project|file(?:_from_template)?)|open_(?:project|file)|(?:close|save)_file|(?:close|save)_all_files|close_project|(?:default_)?settings|print/i}

  devise_for :users, path: 'user', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: ''
  }

end

app/models/directory.rb
class Directory < ActiveRecord::Base

  extend ActsAsTree::TreeView

  acts_as_tree

  belongs_to :project

  has_many :child, class_name: 'Directory', foreign_key: 'parent_id'
  belongs_to :parent, class_name: 'Directory', foreign_key: 'parent_id'


  validates_presence_of :name

  accepts_nested_attributes_for :child

  has_many :data_sets

  before_validation do
    d = Directory.where(parent_id: self.parent_id, name: self.name, project_id: self.project_id)
    return if d.count.zero?
    if self.new_record?
      errors.add(:name, 'Directory with this name already exists.') if !d.count.zero?
    else
      errors.add(:name, 'Directory with this name already exists.') if self.id && d[0].id != self.id && !d.count.zero?
    end
  end

  before_destroy do
    self.files.destroy_all
    self.child.each { |dir| dir.files.destroy_all; dir.destroy! }
  end

  def files
    self.data_sets
  end

end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController

  include DirectoriesHelper

  #before_action :set_directory, only: [:show, :edit, :update]

  # GET /directories
  # GET /directories.json
  def index
    params[:project] = URI.parse(URI.encode(params[:project])).to_s if params[:project]
    if session[:project_id].present?
      if params[:project].present?
        @project = Project.find_by(id: session[:project_id], project_url: params[:project].sub('.html', '')) || (page_not_found and return)
      else
        @project = Project.find(session[:project_id]) || (page_not_found and return)
      end
    elsif session[:project_id].nil? && params[:project].present?
      @project = Project.find_by(project_url: params[:project].sub('.html', '')) || (page_not_found and return)
      session[:project_id] = @project.id
    else
      page_not_found and return
    end
    @directories = @project.directories
    @opened_files = DataSet.where(opened: true, project_id: @project.id)

    @showed = []
  end

  def get_tree
    @showed = []
    @directories = Directory.where project_id: session[:project_id]
    render 'get_tree.js.erb'
  end
  # GET /directories/1
  # GET /directories/1.json
  def show
  end

  # GET /directories/new
  def new
    @directory = Directory.new
    render :new, layout: false if request.xhr?
  end

  # GET /directories/1/edit
  def edit
    render :edit, layout: false
  end

  # POST /directories
  # POST /directories.json
  def create
    @directory = Directory.new(directory_params)
    @directory.project_id = session[:project_id]
    respond_to do |format|
      if @directory.save
        format.html { render text: 'created', layout: false, status: :created }
        format.json { render json: @directory.errors, status: :created }
      else
        params[:id] = @directory.parent_id
        format.html { render action: 'new', layout: false }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directories/1
  # PATCH/PUT /directories/1.json
  def update
    @directory.project_id = session[:project_id]
    respond_to do |format|
      if @directory.update(directory_params)
        format.html { render text: 'created', layout: false, status: :created }
        format.json { head :no_content }
      else
        params[:id] = @directory.parent_id
        format.html { render action: 'edit', layout: false }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directories/1
  # DELETE /directories/1.json
  def destroy
    Directory.find(params[:id]).destroy!

    respond_to do |format|
      format.html { render text: 'created', layout: false, status: :created }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_directory
      @directory = Directory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def directory_params
      params.require(:directory).permit(:name, :path, :parent_id)
    end
end

app/helpers/directories_helper.rb
module DirectoriesHelper

  def nested_directory(directories, showed = [])
    directories.map do |directory, sub_directory|
      return if directory.id == directory.parent_id
      next if showed.include? directory.id
      content_tag(:ul, render(directory))
    end.join.html_safe
  end

  def directory_path dir
    file_path = dir.name if dir.present? && dir.parent_id != -1
    while dir.parent
      file_path += '/' + dir.name
      dir = dir.parent
    end
    file_path
  end
  def nested_directory_tree(directories, showed = [])
    directories.map do |directory, sub_directory|
      return if directory.id == directory.parent_id
      next if showed.include? directory.id
      render(directory)
    end.join(', ').html_safe
  end
end

app/views/directories/_dialog.html.erb
<ul id="directory_context">
  <li><a id="new_file" href="#"><%= t 'new_file' %></a></li>
  <li><a id="new_file_from_template" href="#"><%= t 'new_file_from_template' %></a></li>
  <li><a id="new_dir" href="#"><%= t 'new_dir' %></a></li>
  <% if !is_root %>
    <li><a id="rename_dir" href="#"><%= t 'rename_dir' %></a></li>
    <li><a id="remove_dir" href="#"><%= t 'remove_dir' %></a></li>
  <% end %>
</ul>

app/views/directories/_directory.html.erb
{"title": "<%= directory.name %>", "key": <%= directory.id %>, "folder": true, "id": <%= directory.id %>, "cuted": <%= session[:cut_id] == directory.id %>, "children": [<%= nested_directory_tree directory.child, @showed %>
<%= raw ", #{render 'files/file', files: directory.files}" if directory.files.any? %>]}
<% @showed << directory.id %>

app/views/directories/_form.html.erb
<%= form_for @directory, remote: true, url: "/directories/#{@directory.id}" do |f| %>

  <% if @directory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directory.errors.count, 'error') %> prohibited this directory from being saved:</h2>

      <ul>
      <% @directory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.hidden_field :parent_id, value: params[:id] if @directory.new_record? %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directories/edit.html.erb
<h1>Editing directory</h1>

<%= render 'form' %>
<%#= link_to 'Show', @directory %> |
<%#= link_to 'Back', directories_path %>

app/views/directories/get_tree.js.erb
[<%= raw nested_directory_tree(@directories, @showed).gsub(/(?:, )+$/, '') %>]

app/views/directories/index.html.erb
<% content_for :left_sidebar do %>
  <nobr>
    <div id="tree">
    </div>
  </nobr>
<% end %>
<%= render 'files/tab' %>

<%#= javascript_tag render template: 'directories/directories.js.erb.coffee' %>
<%#= javascript_tag render template: 'files/files.js.erb.coffee' %>

app/views/directories/new.html.erb
<h1>New directory</h1>

<%= render 'form' %>

<%= link_to 'Back', directories_path unless request.xhr? %>

app/views/directories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @directory.name %>
</p>

<p>
  <strong>Path:</strong>
  <%= @directory.path %>
</p>

<p>
  <strong>Project:</strong>
  <%= @directory.project_id %>
</p>

<%= link_to 'Edit', edit_directory_path(@directory) %> |
<%= link_to 'Back', directories_path %>