config/routes.rb
Ide::Application.routes.draw do

  get '/directories/get_tree', to: 'directories#get_tree'
  post '/projects/setSession', to: 'projects#setSession'
  resources :directories
  delete '/directories', to: 'directories#destroy'

  resources :data_sets, controller: 'files', path: 'files'

  get '/projects/:action', to: 'projects#:action', constraints: {action: /open|close/i}
  resources :projects

  root 'projects#index'
  get '/:project', to: 'directories#index', constraints: {project: /[-_.a-z0-9а-яёЁ%]+/i}

  get 'file/:action', to: 'files#:action', constraints: {action: /index|new_(?:project|file(?:_from_template)?)|open_(?:project|file)|(?:close|save)_file|(?:close|save)_all_files|close_project|(?:default_)?settings|print/i}

  devise_for :users, path: 'user', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: ''
  }

end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_action :set_file, only: [:show, :edit, :update, :destroy]
  layout false

  def index
  end

  def new_project
  end

  def open_project
  end

  def new_file
    @file = DataSet.new
    if request.xhr?
      render :new_file, layout: false
    end
  end

  def new_file_from_template
  end

  def open_file
    head :bad_request and return unless request.xhr? or params[:id].present?
    @file = DataSet.find_by_id(params[:id]) || page_not_found
    @file.update(opened: true)
    render 'files/_file.js.erb.coffee', locals: {file: @file } if request.xhr?
  end

  def close_file
    head :bad_request and return unless request.xhr? or params[:id].present?
    DataSet.find_by_id(params[:id]).update(opened: false)
    render 'files/delete_file.js.erb.coffee', locals: {id: params[:id] }
  end

  def close_all_files
    head :bad_request and return unless request.xhr?
    DataSet.update_all(opened: false)
    render text: 'ok'
  end

  def save_file
    head :bad_request and return unless request.xhr? or params[:id].present? or params[:text].present?
    render text: DataSet.find_by_id(params[:id]).update(text: params[:text])
  end

  def save_all_files
  end

  def close_project
  end

  def settings
  end

  def default_settings
  end

  def print
  end

  # GET /files/1
  # GET /files/1.json
  def show
  end

  # GET /files/new
  def new
    @file = DataSet.new
  end

  # GET /files/1/edit
  def edit
  end

  # POST /files
  # POST /files.json
  def create
    @file = DataSet.new(file_params)
    @file.project_id = session[:project_id]
    @file.directory_id = params[:id] if params[:id]
    respond_to do |format|
      if @file.save
        format.html { render text: 'created', layout: false, status: :created }
        format.json { render json: @file.errors, status: :created }
      else
        params[:id] = @file.directory_id
        format.html { render action: 'new_file', layout: false }
        format.json { render json: @file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /files/1
  # PATCH/PUT /files/1.json
  def update
    @file.project_id = session[:project_id]
    respond_to do |format|
      if @file.update(file_params)
        format.html { render text: 'created', layout: false, status: :created }
        format.json { head :no_content }
      else
        params[:id] = @file.directory_id
        format.html { render action: 'edit', layout: false }
        format.json { render json: @file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /files/1
  # DELETE /files/1.json
  def destroy
    @file.destroy
    respond_to do |format|
      format.html { render text: 'created', layout: false, status: :created }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file
      @file = DataSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_params
      params.require(:data_set).permit(:name, :text, :directory_id)
    end
end

app/helpers/files_helper.rb
module FilesHelper
  def file_type_image extension = nil
    filename = "extensions/file-extension-#{extension}-icon.png"
    filename = 'extensions/default-icon.png' unless File.exist?("#{Rails.root}/app/assets/images/#{filename}")
    image_tag image_path(filename), class: 'file-type-icon'
  end
end

app/views/files/_dialog.html.erb
<ul id="context">
  <% if tab %>
    <li><a id="save_file" href="#"><%= t 'save' %></a></li>
    <li><a id="close_file" href="#"><%= t 'close' %></a></li>
    <li><a id="close_all_files" href="#"><%= t 'close_all' %></a></li>
  <% else %>
    <li><a id="rename_file" href="#"><%= t 'rename' %></a></li>
    <li><a id="remove_file" href="#"><%= t 'remove' %></a></li>
  <% end %>
</ul>

app/views/files/_editor_dialog.html.erb
<ul id="editor_context" class="nav">
  <% if cut %>
    <li><%= link_to raw("#{t('cut')} <span style='float:right'>Ctrl+X</span>"), '#', id: 'cut' %></li>
    <li><%= link_to raw("#{t('copy')} <span style='float:right'>Ctrl+C</span>"), '#', id: 'copy' %></li>
    <li><%= link_to raw("#{t('paste')} <span style='float:right'>Ctrl+V</span>"), '#', id: 'paste' %></li>
  <% end %>
  <li><%= link_to t('copy_path'), '#', id: 'copy_path' %></li>
  <li class="divider"></li>
  <li><a id="save_file" href="#"><%= t 'save' %></a></li>
  <li><a id="close_file" href="#"><%= t 'close' %></a></li>
  <li><a id="close_all_files" href="#"><%= t 'close_all' %></a></li>
  <li><a id="find" href="#"><%= t 'find' %></a></li>
  <li><%= link_to t('find'), '#', id: 'find' %></li>
  <li><%= link_to t('select_all'), '#', id: 'select_all' %></li>
  <li><%= link_to t('unselect'), '#', id: 'unselect' %></li>
  <li class="divider"></li>
  <li><%= link_to t('delete'), '#', id: 'delete' %></li>
</ul>

app/views/files/_file.html.erb
<% ret = [] %>
<% files.each do |f| %>
    <% ret << "{\"title\": \"#{f.name}\", \"key\": #{f.id}, \"id\": #{f.id}, \"cuted\": #{session[:cut_id] == f.id}}" %>
<% end %>
<%= raw ret.join ', ' %>

app/views/files/_form.html.erb
<%= form_for @file, remote: true do |f| %>
  <% if @file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file.errors.count, "error") %> prohibited this file from being saved:</h2>

      <ul>
      <% @file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.hidden_field :directory_id, value: params[:id] if @file.new_record?  %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/files/_tab.html.erb
<div id="files">
  <ul class="nav nav-tabs" role="tablist">
    <% @opened_files.each do |file| %>
      <li>
        <a class="file<%= file.id %>" href="#file<%= file.id %>" role="tab" data-toggle="tab" title="<%= create_url directory_path(file.directory), file.name %>">
          <%= file_type_image file.extension %> <%= file.name %>
          <span class="close_tab" data-id="<%= file.id %>"> × </span>
        </a>
      </li>
    <% end %>
  </ul>
  <div class="tab-content">
    <% @opened_files.each do |file| %>
      <div class="tab-pane">
        <%= render(partial: "files/text", locals: {id: file.id}) %>
      </div>
    <% end %>
  </div>
</div>

app/views/files/_text.html.erb
<% @file = DataSet.find_by_id(id) %>
<div id="file<%= @file.id %>" style="display: block">

  <div id="file_text<%= @file.id %>" class="code"  data-editor="<%= @file.extension %>"><%= @file.text %></div>

</div>
<%= simple_form_for @file do |f| %>
    <%= f.text_area :text, id: "data_set_text_#{@file.id}" %>
<% end %>

<%= javascript_tag render template: 'files/ace.js.erb' %>

app/views/files/ace.js.erb
modes = {
  abap: 'abap',
  actionscript: 'actionscript',
  as: 'actionscript',
  ada: 'ada',
  apache_conf: 'apache_conf',
  htacess: 'apache_conf',
  asciidoc: 'asciidoc',
  assembly_x86: 'assembly_x86',
  autohotkey: 'autohotkey',
  batchfile: 'batchfile',
  c9search: 'c9search',
  cpp: 'c_cpp',
  c: 'c_cpp',
  objective_c: 'c_cpp',
  cirru: 'cirru',
  clojure: 'clojure',
  cobol: 'cobol',
  coffee: 'coffee',
  coldfusion: 'coldfusion',
  csharp: 'csharp',
  cs: 'csharp',
  css: 'css',
  curly: 'curly',
  d: 'd',
  dart: 'dart',
  diff: 'diff',
  dot: 'dot',
  erlang: 'erlang',
  ejs: 'ejs',
  forth: 'forth',
  ftl: 'ftl',
  gherkin: 'gherkin',
  glsl: 'glsl',
  golang: 'golang',
  groovy: 'groovy',
  haml: 'haml',
  handlebars: 'handlebars',
  haskell: 'haskell',
  haxe: 'haxe',
  html: 'html',
  html_ruby: 'html_ruby',
  erb: 'html_ruby',
  ini: 'ini',
  jack: 'jack',
  jade: 'jade',
  java: 'java',
  javascript: 'javascript',
  json: 'json',
  jsoniq: 'jsoniq',
  jsp: 'jsp',
  jsx: 'jsx',
  julia: 'julia',
  latex: 'latex',
  less: 'less',
  liquid: 'liquid',
  lisp: 'lisp',
  livescript: 'livescript',
  logiql: 'logiql',
  lsl: 'lsl',
  lua: 'lua',
  luapage: 'luapage',
  lucene: 'lucene',
  makefile: 'makefile',
  matlab: 'matlab',
  markdown: 'markdown',
  mel: 'mel',
  mysql: 'mysql',
  mushcode: 'mushcode',
  nix: 'nix',
  objectivec: 'objectivec',
  ocaml: 'ocaml',
  pascal: 'pascal',
  perl: 'perl',
  pgsql: 'pgsql',
  php: 'php',
  phtml: 'php',
  powershell: 'powershell',
  prolog: 'prolog',
  properties: 'properties',
  protobuf: 'protobuf',
  python: 'python',
  r: 'r',
  rdoc: 'rdoc',
  rhtml: 'rhtml',
  ruby: 'ruby',
  rb: 'ruby',
  rust: 'rust',
  sass: 'sass',
  scad: 'scad',
  scala: 'scala',
  smarty: 'smarty',
  scheme: 'scheme',
  scss: 'scss',
  sh: 'sh',
  sjs: 'sjs',
  space: 'space',
  snippets: 'snippets',
  soy_template: 'soy_template',
  sql: 'sql',
  stylus: 'stylus',
  svg: 'svg',
  tcl: 'tcl',
  tex: 'tex',
  text: 'text',
  txt: 'text',
  textile: 'textile',
  toml: 'toml',
  twig: 'twig',
  typescript: 'typescript',
  visualbasic: 'vbscript',
  vb: 'vbscript',
  vba: 'vbscript',
  velocity: 'velocity',
  verilog: 'verilog',
  xml: 'xml',
  xquery: 'xquery',
  yaml: 'yaml'
}

mode = modes[$("#file_text<%= @file.id %>").attr('data-editor')] ? modes[$("#file_text<%= @file.id %>").attr('data-editor')] : 'javascript'

ace.require('ace/ext/language_tools')

editor = ace.edit("file_text<%= @file.id %>")
editor.getSession().setUseWorker(true);
editor.getSession().setUseWrapMode(true);
editor.getSession().setUseWrapMode(true);

editor.setOptions({
  enableBasicAutocompletion: true
});

editor.setHighlightActiveLine(true);
editor.renderer.setShowGutter(true)
editor.setFontSize('15px')
editor.getSession().setMode("ace/mode/" + mode)
editor.setTheme("ace/theme/xcode")
$("#file_text<%= @file.id %>").show()
$("#file_text<%= @file.id %>").children().show()

var id, undoManager
$(window).load(function() {
  id = $("#files ul li a")[0].className.substring(4)
  undoManager = ace.edit("file_text" + id).getSession().getUndoManager()
})
$(document).on('click', function() {
  $("#editor_context").remove()
})
$(document).on('click', "#files ul li a", function() {
  if(!this.className)
    return
  id = this.className.substring(4)
  undoManager = ace.edit("file_text" + id).getSession().getUndoManager()
})
editor.on('input', function() {
  var el = $(".active").children("a")
  undoManager.hasRedo() ? $("#redo").parent().removeClass('disabled') : $("#redo").parent().addClass('disabled')
  if(!undoManager.hasUndo())
  {
    $('.unsaved').remove()
    $("#undo").parent().addClass('disabled')
  }
  else
    if (-1 === el.html().indexOf("*"))
    {
      $(".active .close_tab").remove()
      $("#undo").parent().removeClass('disabled')
      el.append('<span class="unsaved">*</span><span class="close_tab" data-id="' + id + '"> × </span>')
    }

})

editor.commands.addCommand({
    name: 'saveFile',
    bindKey: {
        win: 'Ctrl-S',
        mac: 'Command-S',
        sender: 'editor|cli'
    },
    exec: function (env, args, request) {
        var id = $($(".active").parent().find(".active")[0]).children().attr("class").substring(4)
        var tmp = ace.edit("file_text" + id)
        $.get("/file/save_file", {id: id, text: tmp.getSession().getValue()}, function (ans) {
            $(".unsaved").remove()
            undoManager.markClean()
        });
    }
});

app/views/files/edit.html.erb
<h1>Editing file</h1>

<%= render 'form' %>

app/views/files/new.html.erb
<h1>New file</h1>

<%= render 'form' %>

<%= link_to 'Back', files_index_path %>

app/views/files/new_file.html.erb
<h1>New file</h1>

<%= render 'form' %>

<%#= link_to 'Back', files_index_path %>

app/views/files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @file.name %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @file.extension %>
</p>

<p>
  <strong>Text:</strong>
  <%= @file.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @file.user_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @file.directory_id %>
</p>

<%#= link_to 'Edit', edit_file_path(@file) %> |
<%#= link_to 'Back', files_index_path %>